// <auto-generated />
namespace NETB401PavelBorisov.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenameCveToCpe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameCveToCpe));
        
        string IMigrationMetadata.Id
        {
            get { return "202404281651242_RenameCveToCpe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
